---
- name: Install K3s
  ansible.builtin.import_tasks: install.yml

- name: Configure kubeconfig environment
  ansible.builtin.import_tasks: environment.yml

- name: Install Helm
  ansible.builtin.import_tasks: helm.yml

- name: Install Argo CD
  ansible.builtin.import_tasks: argocd.yml
