---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediaserver
  namespace: argocd
spec:
  project: mediaserver
  source:
    repoURL: https://github.com/algebananazzzzz/HomeLab.git
    targetRevision: HEAD
    path: argocd/mediaserver
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
