---
- name: Initial server check
  hosts: home
  become: true

  tasks:
    - name: Ping the server
      ansible.builtin.ping:

    - name: Touch init marker
      ansible.builtin.file:
        path: /tmp/ansible_init_marker
        state: touch
        mode: "0644"
